### ISSUE TITLE
Cannot run FIAT in Python by importing it as a module

### ISSUE THREAD

**Issue by frederique-hub** [Deltares/Delft-FIAT#98]
### Delft-FIAT version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have checked that this bug exists on the latest version of Delft-FIAT.

### Reproducible Example

Please check my postbox in the 'fromSarah' folder, you can install the environment from and environment.yml file there and run the script.

### Current behaviour

We get the following error:

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "n:\Deltabox\Postbox\Groen,de Frederique\fromSarah\salinization_test.py", line 131, in <module>
    fm.run()
  File "C:\Repositories\Delft-FIAT\src\fiat\main.py", line 59, in run
    model = GeomModel(self.cfg)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\Delft-FIAT\src\fiat\models\geom.py", line 58, in __init__
    super().__init__(cfg)
  File "C:\Repositories\Delft-FIAT\src\fiat\models\base.py", line 51, in __init__
    self._mp_manager = Manager()
                       ^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\managers.py", line 563, in start
    self._process.start()
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "C:\ProgramData\mambaforge\envs\salinization_fiat\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

Exception ignored in: <function GeomModel.__del__ at 0x0000026B9783AB60>
Traceback (most recent call last):
  File "C:\Repositories\Delft-FIAT\src\fiat\models\geom.py", line 65, in __del__
    BaseModel.__del__(self)
  File "C:\Repositories\Delft-FIAT\src\fiat\models\base.py", line 65, in __del__
    self._mp_manager.shutdown()
    ^^^^^^^^^^^^^^^^
AttributeError: 'GeomModel' object has no attribute '_mp_manager'`

### Desired behaviour

Being able to run FIAT through importing it as a module

**Comment by dalmijn** [comment]
This is not a FIAT bug, but something that occurs when using `multiprocessing`, this doesn't mean it cannot be imported as a module.
